=== tarzanislav/evita/evita.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Popis formátu exportu a importu programu EviTA (verzia formátu 1). -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:simpleType name="Stav">
    <xs:annotation><xs:documentation>Stav položky.</xs:documentation></xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="v prevádzke" />
      <xs:enumeration value="v sklade" />
      <xs:enumeration value="v oprave" />
      <xs:enumeration value="vyradené" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="EviTA">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Kategorie" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Kategoria" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nazov" type="xs:string" use="required" />
                  <xs:attribute name="aktivna" type="xs:boolean" default="true" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Miestnosti" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Miestnost" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nazov" type="xs:string" use="required" />
                  <xs:attribute name="budova" type="xs:string" />
                  <xs:attribute name="poznamka" type="xs:string" />
                  <xs:attribute name="aktivna" type="xs:boolean" default="true" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Osoby" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Osoba" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="meno" type="xs:string" />
                  <xs:attribute name="priezvisko" type="xs:string" use="required" />
                  <xs:attribute name="funkcia" type="xs:string" />
                  <xs:attribute name="aktivna" type="xs:boolean" default="true" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Polozky">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Polozka" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="Nazov" type="xs:string" />
                    <xs:element name="Kategoria" type="xs:string" minOccurs="0" />
                    <xs:element name="Miestnost" type="xs:string" minOccurs="0" />
                    <xs:element name="Pridelene" type="xs:string" minOccurs="0" />
                    <xs:element name="Vyrobca" type="xs:string" minOccurs="0" />
                    <xs:element name="Model" type="xs:string" minOccurs="0" />
                    <xs:element name="SerioveCislo" type="xs:string" minOccurs="0" />
                    <xs:element name="InventarneCislo" type="xs:string" minOccurs="0" />
                    <xs:element name="Ean" type="xs:string" minOccurs="0" />
                    <xs:element name="Stav" type="Stav" minOccurs="0" />
                    <xs:element name="DatumNakupu" type="xs:date" minOccurs="0" />
                    <xs:element name="Cena" type="xs:decimal" minOccurs="0" />
                    <xs:element name="ZarukaDo" type="xs:date" minOccurs="0" />
                    <xs:element name="DalsiaRevizia" type="xs:date" minOccurs="0" />
                    <xs:element name="DatumPridania" type="xs:dateTime" minOccurs="0" />
                    <xs:element name="DatumZmeny" type="xs:dateTime" minOccurs="0" />
                    <xs:element name="DatumVyradenia" type="xs:date" minOccurs="0" />
                    <xs:element name="DovodVyradenia" type="xs:string" minOccurs="0" />
                    <xs:element name="Poznamka" type="xs:string" minOccurs="0" />
                  </xs:all>
                  <xs:attribute name="guid" type="xs:string" />
                  <xs:attribute name="prirastkoveCislo" type="xs:positiveInteger" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Historia" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Zmena" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="guidPolozky" type="xs:string" />
                  <xs:attribute name="prirastkoveCislo" type="xs:int" use="required" />
                  <xs:attribute name="nazovPolozky" type="xs:string" />
                  <xs:attribute name="cas" type="xs:dateTime" use="required" />
                  <xs:attribute name="pouzivatel" type="xs:string" />
                  <xs:attribute name="akcia" type="xs:string" use="required" />
                  <xs:attribute name="pole" type="xs:string" />
                  <xs:attribute name="staraHodnota" type="xs:string" />
                  <xs:attribute name="novaHodnota" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="TypyUdalosti" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TypUdalosti" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nazov" type="xs:string" use="required" />
                  <xs:attribute name="farba" type="xs:string" />
                  <xs:attribute name="aktivny" type="xs:boolean" default="true" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Udalosti" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Udalost" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Popis" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                  <xs:attribute name="guid" type="xs:string" />
                  <xs:attribute name="nazov" type="xs:string" use="required" />
                  <xs:attribute name="typ" type="xs:string" />
                  <xs:attribute name="druh" type="xs:string" />
                  <xs:attribute name="zaciatok" type="xs:dateTime" use="required" />
                  <xs:attribute name="koniec" type="xs:dateTime" />
                  <xs:attribute name="celyDen" type="xs:boolean" default="false" />
                  <xs:attribute name="opakovanie" type="xs:string" />
                  <xs:attribute name="opakovanieDo" type="xs:date" />
                  <xs:attribute name="pripomienka" type="xs:string" />
                  <xs:attribute name="polozkaGuid" type="xs:string" />
                  <xs:attribute name="polozkaCislo" type="xs:int" />
                  <xs:attribute name="miestnost" type="xs:string" />
                  <xs:attribute name="osoba" type="xs:string" />
                  <xs:attribute name="stav" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Ulohy" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Uloha" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Popis" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                  <xs:attribute name="guid" type="xs:string" />
                  <xs:attribute name="text" type="xs:string" use="required" />
                  <xs:attribute name="termin" type="xs:date" />
                  <xs:attribute name="priorita" type="xs:string" />
                  <xs:attribute name="hotovo" type="xs:boolean" default="false" />
                  <xs:attribute name="datumHotovo" type="xs:dateTime" />
                  <xs:attribute name="vytvorene" type="xs:dateTime" />
                  <xs:attribute name="polozkaGuid" type="xs:string" />
                  <xs:attribute name="polozkaCislo" type="xs:int" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Poznamky" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Poznamka" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Text" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                  <xs:attribute name="guid" type="xs:string" />
                  <xs:attribute name="nazov" type="xs:string" use="required" />
                  <xs:attribute name="farba" type="xs:string" />
                  <xs:attribute name="pripnuta" type="xs:boolean" default="false" />
                  <xs:attribute name="vytvorene" type="xs:dateTime" />
                  <xs:attribute name="zmenene" type="xs:dateTime" />
                  <xs:attribute name="datum" type="xs:date" />
                  <xs:attribute name="polozkaGuid" type="xs:string" />
                  <xs:attribute name="polozkaCislo" type="xs:int" />
                  <xs:attribute name="udalostGuid" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="verziaFormatu" type="xs:int" />
      <xs:attribute name="program" type="xs:string" />
      <xs:attribute name="vytvorene" type="xs:dateTime" />
      <xs:attribute name="pocitac" type="xs:string" />
      <xs:attribute name="poslednePrirastkoveCislo" type="xs:int" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tarzanislav/evita/EviTA_vzor_XML.xml
<?xml version="1.0" encoding="utf-8"?>
<EviTA xsi:noNamespaceSchemaLocation="evita.xsd" verziaFormatu="1" program="EviTA 0.7.141" vytvorene="2026-10-22T07:12:59" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Kategorie>
    <Kategoria nazov="notebook" aktivna="true" />
    <Kategoria nazov="tlačiareň" aktivna="true" />
    <Kategoria nazov="projektor" aktivna="true" />
    <Kategoria nazov="príslušenstvo" aktivna="true" />
    <Kategoria nazov="PC" aktivna="true" />
  </Kategorie>
  <Miestnosti>
    <Miestnost nazov="Kancelária 101" budova="A" aktivna="true" />
    <Miestnost nazov="Sekretariát" budova="A" aktivna="true" />
    <Miestnost nazov="Učebňa 12" budova="B" aktivna="true" />
    <Miestnost nazov="Sklad" budova="B" aktivna="true" />
  </Miestnosti>
  <Osoby>
    <Osoba meno="Ján" priezvisko="Novák" funkcia="účtovník" aktivna="true" />
    <Osoba meno="Mária" priezvisko="Kováčová" funkcia="učiteľka" aktivna="true" />
  </Osoby>
  <Polozky>
    <Polozka prirastkoveCislo="1">
      <Nazov>Notebook Dell Latitude 5540</Nazov>
      <Kategoria>notebook</Kategoria>
      <Miestnost>Kancelária 101</Miestnost>
      <Pridelene>Ján Novák</Pridelene>
      <Vyrobca>Dell</Vyrobca>
      <Model>Latitude 5540</Model>
      <SerioveCislo>5CD1234XYZ</SerioveCislo>
      <InventarneCislo>INV-2026-001</InventarneCislo>
      <Stav>v prevádzke</Stav>
      <DatumNakupu>2026-03-15</DatumNakupu>
      <Cena>1089.00</Cena>
      <ZarukaDo>2029-03-15</ZarukaDo>
      <DatumPridania>2026-03-16T00:00:00</DatumPridania>
      <Poznamka>nabíjačka v taške</Poznamka>
    </Polozka>
    <Polozka prirastkoveCislo="2">
      <Nazov>Tlačiareň HP LaserJet Pro M404dn</Nazov>
      <Kategoria>tlačiareň</Kategoria>
      <Miestnost>Sekretariát</Miestnost>
      <Vyrobca>HP</Vyrobca>
      <Model>LaserJet Pro M404dn</Model>
      <SerioveCislo>PHBQK12345</SerioveCislo>
      <InventarneCislo>INV-2025-014</InventarneCislo>
      <Stav>v prevádzke</Stav>
      <DatumNakupu>2025-11-04</DatumNakupu>
      <Cena>289.90</Cena>
      <ZarukaDo>2027-11-04</ZarukaDo>
      <DalsiaRevizia>2027-05-01</DalsiaRevizia>
      <DatumPridania>2025-11-05T00:00:00</DatumPridania>
    </Polozka>
    <Polozka prirastkoveCislo="3">
      <Nazov>Projektor Epson EB-W51</Nazov>
      <Kategoria>projektor</Kategoria>
      <Miestnost>Učebňa 12</Miestnost>
      <Pridelene>Mária Kováčová</Pridelene>
      <Vyrobca>Epson</Vyrobca>
      <Model>EB-W51</Model>
      <SerioveCislo>X5LK0123456</SerioveCislo>
      <Stav>v oprave</Stav>
      <DatumNakupu>2024-09-02</DatumNakupu>
      <Cena>459.00</Cena>
      <ZarukaDo>2026-09-02</ZarukaDo>
      <DatumPridania>2024-09-03T00:00:00</DatumPridania>
      <Poznamka>nesvieti lampa, v servise od 10. 10. 2026</Poznamka>
    </Polozka>
    <Polozka prirastkoveCislo="4">
      <Nazov>Monitor Dell P2422H</Nazov>
      <Kategoria>príslušenstvo</Kategoria>
      <Miestnost>Sklad</Miestnost>
      <Vyrobca>Dell</Vyrobca>
      <Model>P2422H</Model>
      <SerioveCislo>CN-0ABC12-34567</SerioveCislo>
      <Stav>v sklade</Stav>
      <DatumNakupu>2026-01-20</DatumNakupu>
      <Cena>179.00</Cena>
      <ZarukaDo>2029-01-20</ZarukaDo>
      <DatumPridania>2026-01-21T00:00:00</DatumPridania>
    </Polozka>
    <Polozka prirastkoveCislo="5">
      <Nazov>PC Lenovo ThinkCentre M70q</Nazov>
      <Kategoria>PC</Kategoria>
      <Miestnost>Učebňa 12</Miestnost>
      <Vyrobca>Lenovo</Vyrobca>
      <Model>ThinkCentre M70q Gen 2</Model>
      <SerioveCislo>MJ0ABCDE</SerioveCislo>
      <Stav>vyradené</Stav>
      <DatumNakupu>2019-08-26</DatumNakupu>
      <Cena>649.00</Cena>
      <ZarukaDo>2022-08-26</ZarukaDo>
      <DatumPridania>2019-08-27T00:00:00</DatumPridania>
      <DatumVyradenia>2026-06-30</DatumVyradenia>
      <DovodVyradenia>poškodená základná doska</DovodVyradenia>
    </Polozka>
  </Polozky>
</EviTA>
